# Generated by Django 5.0.6 on 2024-09-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_condition_item_provenance_alter_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='creator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
