# Generated by Django 5.0.6 on 2025-01-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_alter_item_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='starting_price',
            field=models.SmallIntegerField(),
        ),
    ]
