# Generated by Django 5.0.6 on 2024-09-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='participant',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='firstname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
