# Generated by Django 5.0.6 on 2024-11-06 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0003_initial'),
        ('item', '0006_item_verified_alter_item_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item'),
        ),
    ]
