# Generated by Django 5.0.6 on 2024-11-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0004_alter_auction_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='ending_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='starting_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
