# Generated by Django 5.0.6 on 2024-11-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0005_alter_auction_ending_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_amount',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
