# Generated by Django 5.0.6 on 2025-01-12 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0006_alter_bid_bid_amount'),
        ('item', '0008_alter_item_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='item.item'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='bid.auction'),
        ),
    ]
